# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael Edmond Landry
title: Experienced Writer Passionate about Improving Software Usability
email: michaeledmondlandry@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
#github_username:  mikelandry
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: mikelandry
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mike and I'm a technical communicator. 

  I have a passion for helping companies make their products and processes more accessible, engaging, and easier to use. With over a decade of experience in technical communication, I can help you bridge the gap between engineers and end users by simplifying complexity and delivering a quality user experience. My goal is to ensure that your users have the right content where and when they need it.

  <a href="https://docs.google.com/document/d/16orwVKEE8fvqeMhCsOD7JhO4U0rwf1JUewp-iOtfY3o/preview" target="_blank">View My Resume</a>

  [Download My Resume](https://docs.google.com/document/d/16orwVKEE8fvqeMhCsOD7JhO4U0rwf1JUewp-iOtfY3o/export?format=pdf)
content:
  - title: Writing Samples # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: API User Guide
        description: | # this will include new lines to allow paragraphs
            <a href="https://help.apperian.com/display/pub/Policies+API+Guide" target="_blank">Policies API Guide</a>

            This collection of topics explains how to use one of Digital.ai’s public APIs, and is aimed primarily at developers. Everything listed under Policies API Guide in the TOC is considered part of the sample.

            I was solely responsible for writing, organizing, and editing all of this content, including the code samples (which I wrote and tested via Postman). I worked closely with developers throughout the writing process to ensure technical accuracy, and with the Product Manager and QA engineer to ensure overall usability. 
      - layout: left
        title: API Reference
        description: | # this will include new lines to allow paragraphs
            <a href="https://apidocs.apperian.com/production/policies.html" target="_blank">Policies API Reference</a>

            This is a detailed API reference topic for the API mentioned in the previous sample. I wrote all of this content including the code samples (we don’t have an auto-generated API doc process). As with the previous example, developers and QA engineers on my scrum team are an invaluable resource in all my API writing.
      - layout: left
        title: Conceptual Info
        description: | # this will include new lines to allow paragraphs
            <a href="https://help.apperian.com/display/pub/About+Policies" target="_blank">About Policies</a>

            This topic provides an in-depth explanation about what policies are and why you’ll use them. I rewrote and reorganized this topic based on content that existed from before I started with the company. The only parts that I didn’t rewrite entirely (except to edit for consistency) are: Policy Status and Policy Evaluation. 

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
